from sqlalchemy.orm import Session

from app.repositories.review_campaign_repository import ReviewCampaignRepository
from app.schemas.review_campaign import ReviewCampaignCreate
from app.analytics.access_analyzer import AccessAnalyzer
from app.governance.review_engine import ReviewEngine
from app.services.audit_service import AuditService


class ReviewCampaignService:
    def __init__(self, db: Session):
        self.db = db
        self.repository = ReviewCampaignRepository(db)

        self.review_engine = ReviewEngine(db)
        self.access_analyzer = AccessAnalyzer(db)
        self.audit_service = AuditService(db)

    def create(self, data: ReviewCampaignCreate):
        return self.repository.create(data)

    def list_all(self):
        return self.repository.list_all()

    def get_by_id(self, record_id: str):
        return self.repository.get_by_id(record_id)
    
    def generate_reviews(self, campaign_id: str):
        campaign = self.repository.get_by_id(campaign_id)

        if campaign is None:
            return None

        generated = 0

        identities = self.access_analyzer.identity_risk()

        for identity in identities:
            review = self.review_engine.create_or_update_review(
                identity_id=identity["identity_id"],
                risk_score=identity["risk_score"],
                risk_level=identity["risk_level"],
                reason="Generated by review campaign.",
            )

            review.campaign_id = campaign.id
            self.db.commit()

            generated += 1

        campaign.total_reviews = generated

        self.db.commit()
        self.db.refresh(campaign)

        self.audit_service.record(
            event_type="CampaignGenerated",
            entity_type="ReviewCampaign",
            entity_id=campaign.id,
            actor=campaign.owner,
            message=f"Generated {generated} reviews.",
            metadata={
                "campaign_name": campaign.name,
                "review_count": generated,
            },
        )

        return campaign