import {
  Box,
  Button,
  Card,
  CardContent,
  Chip,
  Divider,
  LinearProgress,
  List,
  ListItemButton,
  Stack,
  Typography,
} from "@mui/material";

import PlayArrowIcon from "@mui/icons-material/PlayArrow";
import ScienceIcon from "@mui/icons-material/Science";

function riskColor(level) {
  if (level === "Critical") return "error";
  if (level === "High") return "warning";
  if (level === "Medium") return "info";
  return "success";
}

export default function AttackSimulationPanel({
  rankedPaths = [],
  selectedPath,
  setSelectedPath,
  runSimulation,
  simulationResult,
  isSimulating,
}) {
  return (
    <Card sx={{ height: "100%" }}>
      <CardContent>
        <Typography variant="h6" fontWeight={900}>
          Attack Simulation
        </Typography>

        <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
          Ranked attack paths generated by the intelligence engine.
        </Typography>

        <List>
          {rankedPaths.map((path) => (
            <ListItemButton
              key={path.path_rank}
              selected={selectedPath?.path_rank === path.path_rank}
              onClick={() => setSelectedPath(path)}
              sx={{ borderRadius: 2, mb: 1 }}
            >
              <Box sx={{ width: "100%" }}>
                <Stack direction="row" justifyContent="space-between">
                  <Typography fontWeight={900}>Path #{path.path_rank}</Typography>

                  <Chip
                    size="small"
                    label={path.risk_level}
                    color={riskColor(path.risk_level)}
                  />
                </Stack>

                <Typography variant="body2">{path.name}</Typography>

                <Typography variant="caption" color="text.secondary">
                  {path.likelihood}% likelihood • {path.estimated_time}
                </Typography>
              </Box>
            </ListItemButton>
          ))}
        </List>

        <Divider sx={{ my: 2 }} />

        {selectedPath && (
          <>
            <Typography variant="subtitle2" fontWeight={900} gutterBottom>
              Selected Simulation
            </Typography>

            <Stack spacing={1} sx={{ mb: 2 }}>
              <Chip label={`Difficulty: ${selectedPath.difficulty}`} />
              <Chip label={`Likelihood: ${selectedPath.likelihood}%`} />
              <Chip label={`Risk: ${selectedPath.total_risk}`} />
            </Stack>

            <Button
              fullWidth
              variant="contained"
              startIcon={<ScienceIcon />}
              onClick={runSimulation}
              disabled={isSimulating}
            >
              {isSimulating ? "Simulating..." : "Simulate MFA Fix"}
            </Button>
          </>
        )}

        {simulationResult && (
          <>
            <Divider sx={{ my: 2 }} />

            <Typography variant="subtitle2" fontWeight={900}>
              Simulation Results
            </Typography>

            <Stack spacing={1.5} sx={{ mt: 2 }}>
              <Box>
                <Stack direction="row" justifyContent="space-between">
                  <Typography color="text.secondary">Current Risk</Typography>
                  <Typography fontWeight={900}>
                    {simulationResult.summary.current_score}
                  </Typography>
                </Stack>
              </Box>

              <Box>
                <Stack direction="row" justifyContent="space-between">
                  <Typography color="text.secondary">Projected Risk</Typography>
                  <Typography fontWeight={900} color="success.main">
                    {simulationResult.summary.projected_score}
                  </Typography>
                </Stack>

                <LinearProgress
                  variant="determinate"
                  value={simulationResult.summary.projected_score}
                  sx={{ mt: 1, height: 8, borderRadius: 10 }}
                  color="success"
                />
              </Box>

              <Chip
                color="success"
                label={`Risk Reduction: ${simulationResult.summary.risk_reduction}`}
                sx={{ fontWeight: 900 }}
              />
            </Stack>
          </>
        )}
      </CardContent>
    </Card>
  );
}