DEFAULT_REVIEW_INTERVAL_DAYS = 30
DEFAULT_DORMANT_ACCOUNT_DAYS = 90
DEFAULT_STALE_PRIVILEGED_ACCOUNT_DAYS = 30

HIGH_RISK_SCORE = 75
MEDIUM_RISK_SCORE = 50
MODERATE_RISK_SCORE = 25

REVIEW_STATUS_PENDING = "Pending"
REVIEW_STATUS_APPROVED = "Approved"
REVIEW_STATUS_REJECTED = "Rejected"
REVIEW_STATUS_NEEDS_REVIEW = "Needs Review"
REVIEW_STATUS_EXPIRED = "Expired"
REVIEW_STATUS_IN_REVIEW = "In Review"
REVIEW_STATUS_REMEDIATION_REQUIRED = "Remediation Required"
REVIEW_STATUS_CLOSED = "Closed"

REVIEW_TYPE_AUTOMATIC = "Automatic"
REVIEW_TYPE_SCHEDULED = "Scheduled"
REVIEW_TYPE_RISK_TRIGGERED = "Risk Triggered"
REVIEW_TYPE_MANUAL = "Manual"
REVIEW_TYPE_EMERGENCY = "Emergency"