"""Link reviews to campaigns

Revision ID: 37bd984da6ce
Revises: 545cbdb98406
Create Date: 2026-07-06 13:07:39.002655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37bd984da6ce'
down_revision: Union[str, Sequence[str], None] = '545cbdb98406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_reviews', sa.Column('campaign_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_access_reviews_campaign_id'), 'access_reviews', ['campaign_id'], unique=False)
    op.create_foreign_key(None, 'access_reviews', 'review_campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'access_reviews', type_='foreignkey')
    op.drop_index(op.f('ix_access_reviews_campaign_id'), table_name='access_reviews')
    op.drop_column('access_reviews', 'campaign_id')
    # ### end Alembic commands ###
