"""Refactor identity model

Revision ID: 4a1a66ba0b8e
Revises: e3b8d84aae04
Create Date: 2026-07-01 08:46:26.562978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a1a66ba0b8e'
down_revision: Union[str, Sequence[str], None] = 'e3b8d84aae04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identities', sa.Column('identity_class', sa.String(length=100), nullable=False))
    op.add_column('identities', sa.Column('status', sa.String(length=100), nullable=False))
    op.add_column('identities', sa.Column('primary_email', sa.String(length=255), nullable=True))
    op.add_column('identities', sa.Column('primary_phone', sa.String(length=50), nullable=True))
    op.add_column('identities', sa.Column('confidence_score', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_identities_email'), table_name='identities')
    op.create_index(op.f('ix_identities_primary_email'), 'identities', ['primary_email'], unique=False)
    op.drop_column('identities', 'last_name')
    op.drop_column('identities', 'department')
    op.drop_column('identities', 'email')
    op.drop_column('identities', 'identity_type')
    op.drop_column('identities', 'employee_id')
    op.drop_column('identities', 'notes')
    op.drop_column('identities', 'organization')
    op.drop_column('identities', 'identity_status')
    op.drop_column('identities', 'manager_identity_id')
    op.drop_column('identities', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identities', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('identities', sa.Column('manager_identity_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('identities', sa.Column('identity_status', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('identities', sa.Column('organization', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('identities', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('identities', sa.Column('employee_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('identities', sa.Column('identity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('identities', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('identities', sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('identities', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_identities_primary_email'), table_name='identities')
    op.create_index(op.f('ix_identities_email'), 'identities', ['email'], unique=False)
    op.drop_column('identities', 'confidence_score')
    op.drop_column('identities', 'primary_phone')
    op.drop_column('identities', 'primary_email')
    op.drop_column('identities', 'status')
    op.drop_column('identities', 'identity_class')
    # ### end Alembic commands ###
