"""Add review campaigns table

Revision ID: 545cbdb98406
Revises: 833d12e85986
Create Date: 2026-07-06 11:40:08.090410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '545cbdb98406'
down_revision: Union[str, Sequence[str], None] = '833d12e85986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_campaigns',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('campaign_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('completed_reviews', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('source_identifier', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_campaigns_name'), 'review_campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_review_campaigns_status'), 'review_campaigns', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_campaigns_status'), table_name='review_campaigns')
    op.drop_index(op.f('ix_review_campaigns_name'), table_name='review_campaigns')
    op.drop_table('review_campaigns')
    # ### end Alembic commands ###
