"""add organizational identities

Revision ID: 730ae1d62204
Revises: bb76da76389f
Create Date: 2026-08-02 15:02:56.887732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730ae1d62204'
down_revision: Union[str, Sequence[str], None] = 'bb76da76389f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizational_identities',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'identity_id', name='uq_organizational_identities_organization_identity')
    )
    op.create_index(op.f('ix_organizational_identities_display_name'), 'organizational_identities', ['display_name'], unique=False)
    op.create_index(op.f('ix_organizational_identities_identity_id'), 'organizational_identities', ['identity_id'], unique=False)
    op.create_index(op.f('ix_organizational_identities_organization_id'), 'organizational_identities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organizational_identities_status'), 'organizational_identities', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_organizational_identities_status'), table_name='organizational_identities')
    op.drop_index(op.f('ix_organizational_identities_organization_id'), table_name='organizational_identities')
    op.drop_index(op.f('ix_organizational_identities_identity_id'), table_name='organizational_identities')
    op.drop_index(op.f('ix_organizational_identities_display_name'), table_name='organizational_identities')
    op.drop_table('organizational_identities')
    # ### end Alembic commands ###
