"""create decision records

Revision ID: 7470c9694a00
Revises: c41f8b72a6e9
Create Date: 2026-07-13 23:29:25.852228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7470c9694a00'
down_revision: Union[str, Sequence[str], None] = 'c41f8b72a6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_records',
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('decision_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=100), nullable=True),
    sa.Column('recommendation_title', sa.String(length=255), nullable=True),
    sa.Column('risk_level', sa.String(length=100), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('decision_confidence', sa.Integer(), nullable=True),
    sa.Column('evidence_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('acceptance_type', sa.String(length=100), nullable=True),
    sa.Column('review_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_status', sa.String(length=100), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('escalated_to', sa.String(length=255), nullable=True),
    sa.Column('external_ticket_reference', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.String(length=100), nullable=False),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('closed_by', sa.String(length=255), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closure_notes', sa.Text(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('source_identifier', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_records_approval_status'), 'decision_records', ['approval_status'], unique=False)
    op.create_index(op.f('ix_decision_records_closed_at'), 'decision_records', ['closed_at'], unique=False)
    op.create_index(op.f('ix_decision_records_decision_type'), 'decision_records', ['decision_type'], unique=False)
    op.create_index(op.f('ix_decision_records_external_ticket_reference'), 'decision_records', ['external_ticket_reference'], unique=False)
    op.create_index(op.f('ix_decision_records_identity_id'), 'decision_records', ['identity_id'], unique=False)
    op.create_index(op.f('ix_decision_records_recommendation_type'), 'decision_records', ['recommendation_type'], unique=False)
    op.create_index(op.f('ix_decision_records_review_due_at'), 'decision_records', ['review_due_at'], unique=False)
    op.create_index(op.f('ix_decision_records_risk_level'), 'decision_records', ['risk_level'], unique=False)
    op.create_index(op.f('ix_decision_records_status'), 'decision_records', ['status'], unique=False)
    op.create_index(op.f('ix_decision_records_verification_status'), 'decision_records', ['verification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_records_verification_status'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_status'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_risk_level'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_review_due_at'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_recommendation_type'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_identity_id'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_external_ticket_reference'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_decision_type'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_closed_at'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_approval_status'), table_name='decision_records')
    op.drop_table('decision_records')
    # ### end Alembic commands ###
