"""add authentication metadata to accounts

Revision ID: bf3a4fbc41fe
Revises: 48973ba592c4
Create Date: 2026-07-03 15:12:33.309560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf3a4fbc41fe'
down_revision: Union[str, Sequence[str], None] = '48973ba592c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "accounts",
        sa.Column("authentication_strength", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "accounts",
        sa.Column("authentication_provider", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "accounts",
        sa.Column(
            "mfa_enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'mfa_enabled')
    op.drop_column('accounts', 'authentication_provider')
    op.drop_column('accounts', 'authentication_strength')
    # ### end Alembic commands ###
