"""Add governance policies table

Revision ID: de646e9a52eb
Revises: 37bd984da6ce
Create Date: 2026-07-06 15:53:32.629437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de646e9a52eb'
down_revision: Union[str, Sequence[str], None] = '37bd984da6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governance_policies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('policy_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=100), nullable=False),
    sa.Column('risk_weight', sa.Integer(), nullable=False),
    sa.Column('conditions_json', sa.JSON(), nullable=True),
    sa.Column('actions_json', sa.JSON(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('source_identifier', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_policies_name'), 'governance_policies', ['name'], unique=False)
    op.create_index(op.f('ix_governance_policies_severity'), 'governance_policies', ['severity'], unique=False)
    op.create_index(op.f('ix_governance_policies_status'), 'governance_policies', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_governance_policies_status'), table_name='governance_policies')
    op.drop_index(op.f('ix_governance_policies_severity'), table_name='governance_policies')
    op.drop_index(op.f('ix_governance_policies_name'), table_name='governance_policies')
    op.drop_table('governance_policies')
    # ### end Alembic commands ###
