"""Create identity attributes table

Revision ID: e683d5d94a32
Revises: 4a1a66ba0b8e
Create Date: 2026-07-01 09:11:47.308604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e683d5d94a32'
down_revision: Union[str, Sequence[str], None] = '4a1a66ba0b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_attributes',
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('attribute_name', sa.String(length=100), nullable=False),
    sa.Column('attribute_value', sa.Text(), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('source_record', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_attributes_identity_id'), 'identity_attributes', ['identity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_attributes_identity_id'), table_name='identity_attributes')
    op.drop_table('identity_attributes')
    # ### end Alembic commands ###
