FROM postgres:17-alpine@sha256:18cfe3ef5e6815560c98237d6216d1e5119702fb0f3894c8785dd58b8bbe5d73

USER root

RUN apk add --no-cache \
        libssl3=3.5.8-r0 \
        libcrypto3=3.5.8-r0 \
    && rm -f /usr/local/bin/gosu

USER postgres